const elysian_file_rom_t rom_fs[] = {
	{.name = (char*) "/ajax.html", .ptr = (uint8_t*) data_ajax_html, .size = sizeof(data_ajax_html)},
	{.name = (char*) "/audio/audio_8khz.mp3", .ptr = (uint8_t*) data_audio_audio_8khz_mp3, .size = sizeof(data_audio_audio_8khz_mp3)},
	{.name = (char*) "/basic_access_auth.html", .ptr = (uint8_t*) data_basic_access_auth_html, .size = sizeof(data_basic_access_auth_html)},
	{.name = (char*) "/css.css", .ptr = (uint8_t*) data_css_css, .size = sizeof(data_css_css)},
	{.name = (char*) "/dynamic_page.html", .ptr = (uint8_t*) data_dynamic_page_html, .size = sizeof(data_dynamic_page_html)},
	{.name = (char*) "/file_download.html", .ptr = (uint8_t*) data_file_download_html, .size = sizeof(data_file_download_html)},
	{.name = (char*) "/file_upload.html", .ptr = (uint8_t*) data_file_upload_html, .size = sizeof(data_file_upload_html)},
	{.name = (char*) "/form_get.html", .ptr = (uint8_t*) data_form_get_html, .size = sizeof(data_form_get_html)},
	{.name = (char*) "/form_post.html", .ptr = (uint8_t*) data_form_post_html, .size = sizeof(data_form_post_html)},
	{.name = (char*) "/gallery.html", .ptr = (uint8_t*) data_gallery_html, .size = sizeof(data_gallery_html)},
	{.name = (char*) "/graphs.html", .ptr = (uint8_t*) data_graphs_html, .size = sizeof(data_graphs_html)},
	{.name = (char*) "/images/img1.jpg", .ptr = (uint8_t*) data_images_img1_jpg, .size = sizeof(data_images_img1_jpg)},
	{.name = (char*) "/images/img2.jpg", .ptr = (uint8_t*) data_images_img2_jpg, .size = sizeof(data_images_img2_jpg)},
	{.name = (char*) "/images/img3.jpg", .ptr = (uint8_t*) data_images_img3_jpg, .size = sizeof(data_images_img3_jpg)},
	{.name = (char*) "/images/img4.jpg", .ptr = (uint8_t*) data_images_img4_jpg, .size = sizeof(data_images_img4_jpg)},
	{.name = (char*) "/images/img5.jpg", .ptr = (uint8_t*) data_images_img5_jpg, .size = sizeof(data_images_img5_jpg)},
	{.name = (char*) "/images/img6.jpg", .ptr = (uint8_t*) data_images_img6_jpg, .size = sizeof(data_images_img6_jpg)},
	{.name = (char*) "/images/img7.jpg", .ptr = (uint8_t*) data_images_img7_jpg, .size = sizeof(data_images_img7_jpg)},
	{.name = (char*) "/images/img8.jpg", .ptr = (uint8_t*) data_images_img8_jpg, .size = sizeof(data_images_img8_jpg)},
	{.name = (char*) "/index.html", .ptr = (uint8_t*) data_index_html, .size = sizeof(data_index_html)},
	{.name = (char*) "/partial_content.html", .ptr = (uint8_t*) data_partial_content_html, .size = sizeof(data_partial_content_html)},
	{.name = (char*) "/redirected_page1.html", .ptr = (uint8_t*) data_redirected_page1_html, .size = sizeof(data_redirected_page1_html)},
	{.name = (char*) "/static_page.html", .ptr = (uint8_t*) data_static_page_html, .size = sizeof(data_static_page_html)},
};
